name: taskingcheck
description: "App Flutter con login usando Firebase"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_messaging: ^16.0.0 # Aunque ya lo tienes, la usaremos para notificaciones avanzadas
  image_picker: ^1.2.0

  # ðŸš€ NUEVOS: Para Notificaciones Locales y Fechas ðŸš€
  flutter_local_notifications: ^19.5.0 # Necesario para programar notificaciones en el dispositivo
  timezone: ^0.10.1                      # Necesario para manejar la zona horaria para notificaciones exactas


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  # Assets (si tienes)
  # assets:
  #   - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icono.png"
